-- BASELINE. Generated by drizzle-kit from the schema as it stood when the
-- project moved off `drizzle-kit push`, then edited by hand in one respect:
-- every statement is IF NOT EXISTS. That is what lets an EXISTING database
-- (production, and any dev database built by push) run the migration flow
-- without a separate "mark as applied" step - this file no-ops there and
-- records itself in drizzle's journal, so every later migration applies
-- normally. On an empty database it creates the schema from scratch.
--
-- Do not edit this file again: it has been applied, and drizzle hashes it.
CREATE TABLE IF NOT EXISTS "user_profiles" (
	"user_id" text PRIMARY KEY NOT NULL,
	"name" text,
	"mode" text DEFAULT 'ai' NOT NULL,
	"goal" text DEFAULT '' NOT NULL,
	"experience" text DEFAULT '' NOT NULL,
	"training_days" integer DEFAULT 4 NOT NULL,
	"equipment" text[] DEFAULT '{}' NOT NULL,
	"age" integer,
	"sex" text,
	"weight" real,
	"weight_unit" text DEFAULT 'kg',
	"goal_weight" real,
	"activity_level" text,
	"rest_days" text[] DEFAULT '{}' NOT NULL,
	"injuries" text,
	"injury_severity" text,
	"priority_muscles" text[] DEFAULT '{}' NOT NULL,
	"daily_calorie_target" integer,
	"daily_step_target" integer,
	"cardio_days" text[] DEFAULT '{}' NOT NULL,
	"cardio_minutes" integer,
	"onboarding_complete" boolean DEFAULT false NOT NULL,
	"onboarding_completed_at" timestamp with time zone,
	"calibration_walkthrough_seen_at" timestamp with time zone,
	"program_page_tour_seen_at" timestamp with time zone,
	"weight_logging_tour_seen_at" timestamp with time zone,
	"dashboard_tour_seen_at" timestamp with time zone,
	"calendar_tour_seen_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "programs" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"week_number" integer NOT NULL,
	"program_name" text NOT NULL,
	"split_type" text NOT NULL,
	"program_highlights" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"days" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"long_term_phase" text,
	"short_term_phase" text,
	"energy_balance" text,
	"training_workload" jsonb,
	"long_term_goal_weight" real,
	"short_term_goal_weight" real,
	"daily_step_target" integer,
	"daily_calorie_target" integer,
	"cardio_intensity" jsonb,
	"start_date" text,
	"schedule" jsonb,
	"phase_segment_index" integer,
	"weeks_in_phase_segment" integer,
	"ai_generated" boolean DEFAULT true NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workout_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"date" text NOT NULL,
	"day_number" integer NOT NULL,
	"week_number" integer NOT NULL,
	"day_label" text,
	"mode" text DEFAULT 'ai' NOT NULL,
	"exercises_logged" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"started_at" timestamp with time zone,
	"duration_seconds" integer,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "checkins" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"week_number" integer NOT NULL,
	"energy" integer NOT NULL,
	"sleep" integer NOT NULL,
	"soreness" text NOT NULL,
	"completion" text,
	"sessions_planned" integer,
	"sessions_logged" integer,
	"missed_session_reason" text,
	"rating_scale_max" integer,
	"hunger_appetite" integer,
	"off_day_deviation" boolean,
	"exercise_issues" text,
	"went_well" text,
	"didnt_go_well" text,
	"sleep_decline" text,
	"digestion_issues" text,
	"notes" text,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "subscriptions" (
	"user_id" text PRIMARY KEY NOT NULL,
	"plan" text DEFAULT 'free' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"current_period_end" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "calendar_colors" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"day_label" text NOT NULL,
	"hex_color" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bodyweight_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"date" text NOT NULL,
	"weight" real NOT NULL,
	"weight_unit" text DEFAULT 'kg' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daily_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"date" text NOT NULL,
	"calories" integer,
	"steps" integer,
	"cardio_type" text,
	"cardio_minutes" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "bodyweight_logs_user_date_idx" ON "bodyweight_logs" USING btree ("user_id","date");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "daily_logs_user_date_idx" ON "daily_logs" USING btree ("user_id","date");
